// <auto-generated />
using System;
using BackEndAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEndAPI.Migrations
{
    [DbContext(typeof(FurijatContext))]
    [Migration("20230614010958_AddedCharityDonators")]
    partial class AddedCharityDonators
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackEndAPI.Data.Entites.CharityDonators", b =>
                {
                    b.Property<int>("DonatorID")
                        .HasColumnType("int");

                    b.Property<int>("CharityID")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DonatorID", "CharityID");

                    b.HasIndex("CharityID");

                    b.ToTable("CharityDonators");
                });

            modelBuilder.Entity("BackEndAPI.Data.Entites.CharityManagment", b =>
                {
                    b.Property<int>("CaseID")
                        .HasColumnType("int");

                    b.Property<int>("CharityID")
                        .HasColumnType("int");

                    b.Property<int>("CreditorID")
                        .HasColumnType("int");

                    b.Property<int>("CreditorCaseID")
                        .HasColumnType("int");

                    b.Property<int>("CreditorID1")
                        .HasColumnType("int");

                    b.Property<int>("Deserves_Debt")
                        .HasColumnType("int");

                    b.Property<int>("PaidAmount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CaseID", "CharityID", "CreditorID");

                    b.HasIndex("CharityID");

                    b.HasIndex("CreditorID1", "CreditorCaseID");

                    b.ToTable("CharityManagment");
                });

            modelBuilder.Entity("BackEndAPI.Data.Entites.Creditor", b =>
                {
                    b.Property<int>("CreditorID")
                        .HasColumnType("int");

                    b.Property<int>("CaseID")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Deserves_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Payment_Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("CreditorID", "CaseID");

                    b.ToTable("Creditor");
                });

            modelBuilder.Entity("BackEndAPI.Models.Charity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("Bank_Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminID");

                    b.HasIndex("UserId");

                    b.ToTable("Charities");
                });

            modelBuilder.Entity("BackEndAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastNaame")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackEndAPI.Data.Entites.Admin", b =>
                {
                    b.HasBaseType("BackEndAPI.Models.User");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("BackEndAPI.Data.Entites.Case", b =>
                {
                    b.HasBaseType("BackEndAPI.Models.User");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarriageStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("BackEndAPI.Data.Entites.Donator", b =>
                {
                    b.HasBaseType("BackEndAPI.Models.User");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Donatores");
                });

            modelBuilder.Entity("BackEndAPI.Data.Entites.CharityDonators", b =>
                {
                    b.HasOne("BackEndAPI.Models.Charity", null)
                        .WithMany("CharityDonators")
                        .HasForeignKey("CharityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Data.Entites.Donator", null)
                        .WithMany("CharityDonators")
                        .HasForeignKey("DonatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEndAPI.Data.Entites.CharityManagment", b =>
                {
                    b.HasOne("BackEndAPI.Data.Entites.Case", null)
                        .WithMany("CharityManagment")
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Charity", null)
                        .WithMany("CharityManagment")
                        .HasForeignKey("CharityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Data.Entites.Creditor", null)
                        .WithMany("CharityManagment")
                        .HasForeignKey("CreditorID1", "CreditorCaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEndAPI.Models.Charity", b =>
                {
                    b.HasOne("BackEndAPI.Data.Entites.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Admin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEndAPI.Data.Entites.Admin", b =>
                {
                    b.HasOne("BackEndAPI.Models.User", null)
                        .WithOne()
                        .HasForeignKey("BackEndAPI.Data.Entites.Admin", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEndAPI.Data.Entites.Case", b =>
                {
                    b.HasOne("BackEndAPI.Models.User", null)
                        .WithOne()
                        .HasForeignKey("BackEndAPI.Data.Entites.Case", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEndAPI.Data.Entites.Donator", b =>
                {
                    b.HasOne("BackEndAPI.Models.User", null)
                        .WithOne()
                        .HasForeignKey("BackEndAPI.Data.Entites.Donator", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEndAPI.Data.Entites.Creditor", b =>
                {
                    b.Navigation("CharityManagment");
                });

            modelBuilder.Entity("BackEndAPI.Models.Charity", b =>
                {
                    b.Navigation("CharityDonators");

                    b.Navigation("CharityManagment");
                });

            modelBuilder.Entity("BackEndAPI.Data.Entites.Case", b =>
                {
                    b.Navigation("CharityManagment");
                });

            modelBuilder.Entity("BackEndAPI.Data.Entites.Donator", b =>
                {
                    b.Navigation("CharityDonators");
                });
#pragma warning restore 612, 618
        }
    }
}
